### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by WaiYanTun25**

### CODE REVIEW

**Comment by WaiYanTun25** [comment]
http://lvh.me:5555/dod/bob1/tasks/6

**Comment by WaiYanTun25** [comment]
http://lvh.me:5555/dod/bob1/tasks/6

**Comment by WaiYanTun25** [comment]
http://lvh.me:5555/dod/bob1/tasks/6

**Comment by waiyantun15395** [comment]
http://lvh.me:5555/dod/bob1/tasks/10

**Review by waiyantun15395 — CHANGES_REQUESTED** [review]
Something fix here

**Review by waiyantun15395 — APPROVED** [review]

**Pull request merged**
